name: Trigger auto deployment for rescueshelter-report

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/rescueshelter-report-AutoDeployTrigger-90ec1b4d-69e0-4196-bb58-eef22925c8a5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RESCUESHELTERREPORT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RESCUESHELTERREPORT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RESCUESHELTERREPORT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.RESCUESHELTERREPORT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RESCUESHELTERREPORT_REGISTRY_PASSWORD }}
          containerAppName: rescueshelter-report
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


